image: ghcr.io/ikoznov/asciidoc_jekyll/fedora:main

variables:
  LC_ALL: C.UTF-8

before_script:
  #- gem install bundler
  - bundle install

#env:
#  stage: test
#  script:
#    - export
#
#test:
#  stage: test
#  script:
#    - bundle exec jekyll build -d test --draft --config _config.yml
#  artifacts:
#    paths:
#    - test
#  rules:
#    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  variables:
    JEKYLL_ENV: production
  script:
    - ./version.sh
    # TODO: use $CI_PROJECT_URL to get --baseurl and --url instead of hardcoding _config-gitlab.yml
    - bundle exec jekyll build -d public --config _config.yml,_config-gitlab.yml,_config-version.yml
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
