# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Igor Koznov"
title_separator: "|"

masthead_title: " "

name: "Igor Koznov"
description: >- # this means to ignore newlines until "baseurl:"
  Personal website

enable_copy_code_button: true
copyright: "Igor Koznov"

author:
  name: "Igor Koznov"
  avatar: "/assets/images/bio-photo.webp"
  bio: "Software developer"
  #location: "Belgrade, Serbia"
  links:
    #- label: "Website"
    #  icon: "fa-solid fa-link"
    #  url: "https://ikoznov.gitlab.io"
    - label: "Email"
      icon: "fa-solid fa-envelope"
      url: "mailto:ikoznov@proton.me"
    - label: "Google Scholar"
      icon: "fa-brands fa-google-scholar"
      url: "https://scholar.google.com/citations?hl=en&user=pB5WTLUAAAAJ"
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/igor-koznov-ba92b5367"
    - label: "GitHub"
      icon: "fa-brands fa-github"
      url: "https://github.com/iKoznov"

# Site Footer
footer:
  links:
    #- label: "Website"
    #  icon: "fa-solid fa-link"
    #  url: "https://ikoznov.gitlab.io"
    - label: "Email"
      icon: "fa-solid fa-envelope"
      url: "mailto:ikoznov@proton.me"
    - label: "Google Scholar"
      icon: "fa-brands fa-google-scholar"
      url: "https://scholar.google.com/citations?hl=en&user=pB5WTLUAAAAJ"
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/igor-koznov-ba92b5367"
    - label: "GitHub"
      icon: "fa-brands fa-github"
      url: "https://github.com/iKoznov"

sass:
  sass_dir: _sass
  style: compressed

#compress_html:
#  clippings: all
#  ignore:
#    envs: development

plugins:
  #- jekyll-remote-theme
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-postfiles
  - jekyll-asciidoc
  #- jekyll-typogrify
  - jekyll-analytics # included in minima
  - jekyll-feed # included in minima
  - jekyll-seo-tag # included in minima
  #- jekyll-archives

#permalink: /:year/:month/:day/:title/
permalink: /posts/:title/

pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

encoding: utf-8

# fixes error to enable es6 syntax
jekyll-minifier:
  uglifier_args:
    harmony: true
  exclude:
    - "assets/js/plugins/smooth-scroll.js"

#remote_theme: JakeSteam/minimaJake
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

minima:
  skin: classic
  nav_pages:
    - portfolio.adoc
    - about.adoc
  social_links:
    - { title: "LinkedIn", icon: linkedin, url: "https://www.linkedin.com/in/igor-koznov-ba92b5367" }
    - { title: "Google Scholar",  icon: google-scholar, url: "https://scholar.google.com/citations?hl=en&user=pB5WTLUAAAAJ" }
    - { title: "GitHub", icon: github, url: "https://github.com/iKoznov" }

asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    icons: font
    source-language: text
    source-highlighter: pygments
    pygments-css: style

show_excerpts: true
google_analytics: G-X2LJQ55K1S # minima feature

include:
  - _pages
exclude:
  - README*
  - LICENSE*
  - Dockerfile
  - .github/
  - .gitlab-ci.yml
  - .idea/

defaults:
  - # without this jekyll-sitemap fails
    scope: { path: "**/*.pdf" }
    values: { sitemap: false }

  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

  # _posts
  - scope:
      path: ""
      type: posts
    values:
      render_with_liquid: false
      layout: single
      classes: wide
      author_profile: true
      show_date: true
      read_time: false
      comments: false
      share: false
      related: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
