# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Igor Koznov personal website
author: { name: Igor Koznov, email: igor.koznov90@protonmail.com }
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  #- jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-postfiles
  - jekyll-asciidoc
  #- jekyll-typogrify
  - jekyll-analytics # included in minima
  - jekyll-feed # included in minima
  - jekyll-seo-tag # included in minima
  #- jekyll-archives

#permalink: /:year/:month/:day/:title/
permalink: /posts/:title/

#remote_theme: JakeSteam/minimaJake
theme: minima
minima:
  skin: classic
  nav_pages:
    - portfolio.adoc
    - about.adoc
  social_links:
    - { title: "LinkedIn", icon: linkedin, url: "https://github.com/jekyll/jekyll" }
    - { title: "Google Scholar",  icon: google-scholar, url: "https://scholar.google.com/citations?hl=en&user=pB5WTLUAAAAJ" }
    - { title: "GitHub", icon: github, url: "https://github.com/iKoznov" }

asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - source-highlighter=rouge
    - source-language=cpp
    - icons=font

show_excerpts: true
google_analytics: G-X2LJQ55K1S # minima feature

exclude:
  - README*
  - LICENSE*
  - Dockerfile
  - .github/
  - .gitlab-ci.yml
  - .idea/

defaults:
  - # without this jekyll-sitemap fails
    scope: { path: "**/*.pdf" }
    values: { sitemap: false }

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
