baseURL: 'https://ikoznov.gitlab.io/blog/'
title: Geekblog
theme: hugo-geekblog

pluralizeListTitles: false

# Geekblog required configuration
pygmentsUseClasses: true
pygmentsCodeFences: true
disablePathToLower: true

# Needed for mermaid shortcodes
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 9

taxonomies:
  author: authors
  tag: tags

mediaTypes:
  application/atom+xml:
    suffixes:
      - xml

outputFormats:
  Atom:
    name: Atom
    mediaType: application/atom+xml
    baseName: feed
    isPlainText: false
    rel: alternate
    isHTML: false
    noUgly: true
    permalinkable: false

outputs:
  home:
    - HTML
    - ATOM
  page:
    - HTML
  section:
    - HTML
  taxonomy:
    - HTML
  term:
    - HTML
    - ATOM
