= GitFlow


В нашем случае есть дополнительные условия к такому gitflow:

- В релизной ветке могут быть изменения, которые не должны попасть в мастер. Но это не частая ситуация, например версия для какого-то заказчика для его внутренних тестов. В данном случае в приложении, например, отличается одна строчка url или какой-нибудь флаг для включения фичи или название версии. В данном случае при мердже в мастер этой резной ветки должен быть сделан в мастер дополнительный откатывающий эти изменения коммит. Таким образом последующие перемердживания будут проходить без конфликтов и изменения будут только в нужных ветках. А если последующие изменения затронут эти отличающиеся куски, то там будет конфликт и нужно будет руками его разрешить, т.е. никакие такие локальные для релиза изменения не попадут случайным образом в мастер.

- И второе, у нас в одном git живут несколько продуктов. У нас релизные ветки будут под продукт, а не под все, что есть в git.

'''

[tikz,,svg,preamble=true]
----
\usepackage{gitdags}
~~~~
\begin{tikzpicture}
  \gitDAG[grow left sep = 2em]{
        A -- rollback B -- {
            C -- D -- E,
            D' -- E'
        } -- merge
  };
\end{tikzpicture}
----

'''

[tikz,,svg,preamble=true]
----
\usepackage{gitdags}
\tikzgraphsset{%
  nudge/.style={/tikz/shift={#1}},
  nudge down/.style={nudge=(270:#1)},
  nudge down/.default=1
}
~~~~
\begin{tikzpicture}
  \gitDAG[grow left sep = 2em]{
        merge C -- {[nudge down] B;} -- A,
        merge C -- A
  };
\end{tikzpicture}
----

'''

[tikz,"gitflow",svg,preamble=true]
----
\usepackage{gitdags}
\tikzgraphsset{%
  nudge/.style={/tikz/shift={#1}},
  nudge down/.style={nudge=(270:#1)},
  nudge down/.default=1
}
~~~~
\begin{tikzpicture}
\gitDAG[grow right sep = 2em]{
  {[nodes=placeholder commits] "..."}  -- A -- B -- C --
  {[nudge down] D -- E}
};
\end{tikzpicture}
----

[bibliography]
== References

* Site about "Release Branching Strategy", http://releaseflow.org[]
